
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Subramaniam V
 */
public class signupPage extends javax.swing.JFrame {

    /**
     * Creates new form signupPage
     */
    public signupPage() {
        initComponents();
        setSize(400,400);
        setResizable(false);
        bgl2.setOpaque(true);
        bgl2.setBackground(Color.yellow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username2 = new javax.swing.JTextField();
        password2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        signup2 = new javax.swing.JButton();
        tandc = new javax.swing.JCheckBox();
        confirm = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        bgl2 = new javax.swing.JLabel();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);
        getContentPane().add(name);
        name.setBounds(143, 79, 140, 30);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("name : ");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(26, 82, 100, 14);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username : ");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(26, 138, 100, 14);
        getContentPane().add(username2);
        username2.setBounds(143, 135, 140, 30);
        getContentPane().add(password2);
        password2.setBounds(143, 184, 140, 30);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("password");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(26, 187, 100, 14);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("confirm password :");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(26, 244, 100, 14);

        signup2.setText("register");
        signup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup2ActionPerformed(evt);
            }
        });
        getContentPane().add(signup2);
        signup2.setBounds(115, 332, 69, 23);

        tandc.setText("I agree to the terms and conditions.");
        tandc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tandcActionPerformed(evt);
            }
        });
        getContentPane().add(tandc);
        tandc.setBounds(70, 290, 207, 23);
        getContentPane().add(confirm);
        confirm.setBounds(143, 241, 140, 30);

        jLabel6.setFont(new java.awt.Font("Harlow Solid Italic", 2, 36)); // NOI18N
        jLabel6.setText("Sign up page:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 20, 200, 40);
        getContentPane().add(bgl2);
        bgl2.setBounds(0, 0, 400, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tandcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tandcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tandcActionPerformed

    private void signup2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup2ActionPerformed
        // TODO add your handling code here:
        String name1 = name.getText();
        String un = username2.getText();
        String pw = new String(password2.getPassword());
        String cpw = new String(confirm.getPassword());
        int x = 0;
        
        if(name1.equals("")){
            JOptionPane.showMessageDialog(null," Enter name!");
            name.setText("");
        }            
        else if(un.equals("")){
            JOptionPane.showMessageDialog(null," Give a username!");
            username2.setText("");
        }
        else if(pw.equals("")){
            JOptionPane.showMessageDialog(null," Enter a password!");
            password2.setText("");
        }
        else if(cpw.equals("")){
            JOptionPane.showMessageDialog(null," Confirm password!");
            confirm.setText("");
        }
        else if(pw.compareTo(cpw)!=0){
            JOptionPane.showMessageDialog(null," passwords don't match!");
            confirm.setText("");
            password2.setText("");
        }
        else if(tandc.isSelected()==false){
            JOptionPane.showMessageDialog(null," agree to the terms and conditions!");
        }
        else{
            LoginPage lp = new LoginPage();
            lp.setVisible(true);
        }
    }//GEN-LAST:event_signup2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signupPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgl2;
    private javax.swing.JPasswordField confirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password2;
    private javax.swing.JButton signup2;
    private javax.swing.JCheckBox tandc;
    private javax.swing.JTextField username2;
    // End of variables declaration//GEN-END:variables
}
