// imports used:
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */

public class frontpage extends javax.swing.JFrame {

    ActionListener action, a2;
    Timer t;
    int x = 0, opacity = 0, d = 1;
    int count = 0;
    public static ImageIcon i;
    public static String name1,name2;

    /**
     * Creates new form frontpage
     */
    public frontpage() {
        initComponents();
    }

    // to show the components after initial graphics on opening:
    void showComponents(){
        l1.setIcon(new ImageIcon("D:\\stick fight\\gamephotos\\sffpb.jpg"));
        head.setIcon(new ImageIcon("D:\\stick fight\\gamephotos\\sffph.jpg"));
        p1n.setVisible(true);
        p2n.setVisible(true);
        jLabel1.setText("Player 1 name");
        jLabel2.setText("Player 2 name");  
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jLabel4.setIcon(new ImageIcon("D:\\stick fight\\gamephotos\\start.jpg"));
        theme1.setVisible(true);
        theme2.setVisible(true);
        theme3.setVisible(true);
    }
    
    // to clear selections and inputs:
    void clear(){
        p1n.setText("");
        p2n.setText("");
        bg1.clearSelection();
        count = 0;
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.ButtonGroup();
        b1 = new javax.swing.JPanel();
        head = new javax.swing.JLabel();
        p1n = new javax.swing.JTextField();
        p2n = new javax.swing.JTextField();
        theme1 = new javax.swing.JRadioButton();
        theme2 = new javax.swing.JRadioButton();
        theme3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
        });

        bg1.add(theme1);
        theme1.setText("Desert");

        bg1.add(theme2);
        theme2.setText("Hills");

        bg1.add(theme3);
        theme3.setText("City");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Choose theme");

        jLabel4.setText("jLabel4");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout b1Layout = new javax.swing.GroupLayout(b1);
        b1.setLayout(b1Layout);
        b1Layout.setHorizontalGroup(
            b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(b1Layout.createSequentialGroup()
                .addGroup(b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(b1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(theme3)
                            .addComponent(theme2)
                            .addComponent(theme1)))
                    .addGroup(b1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(b1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(b1Layout.createSequentialGroup()
                .addGroup(b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(b1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(b1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(p1n, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p2n, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 157, Short.MAX_VALUE))
        );
        b1Layout.setVerticalGroup(
            b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(b1Layout.createSequentialGroup()
                .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 11, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(theme1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(theme2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(theme3)
                .addGap(96, 96, 96)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );

        getContentPane().add(b1);
        b1.setBounds(0, 0, 500, 350);
        getContentPane().add(l1);
        l1.setBounds(0, 0, 500, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        super.setSize(360,410);
        b1.setBounds(super.getBounds());
        l1.setBounds(super.getBounds());
        b1.setOpaque(false);
        p1n.setVisible(false);
        p2n.setVisible(false);
        theme1.setVisible(false);
        theme2.setVisible(false);
        theme3.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        l1.setIcon(new ImageIcon("D:\\stick fight\\gamephotos\\sffpb2.jpg"));
        action = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){   
                b1.setBackground(new Color(0,0,0,opacity));
                b1.setOpaque(true);
                opacity+=d;
                if(opacity>1)
                    t.setDelay(150);
                if(opacity>=45){
                    showComponents();
                    t.stop();
                }                
            }
        };
        t = new Timer(100,action);
        t.setDelay(1000);
        t.setRepeats(true);
        t.start();           
    }//GEN-LAST:event_formWindowOpened
    // to skip the initial graphics:
    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked
        // TODO add your handling code here:
        showComponents();
        if(t.isRunning())
        t.stop();
    }//GEN-LAST:event_b1MouseClicked
    // for the label acting as start button: 
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        if(!p1n.getText().equals("")){
            count++;
            name1 = p1n.getText();
        }
        else{
            JOptionPane.showMessageDialog(this, "player 1, enter name");
            clear();
        }
        if(!p2n.getText().equals("")){
            count++;
            name2 = p2n.getText();
        }
        else{
            JOptionPane.showMessageDialog(this, "player 2, enter name");
            clear();
        }
        if(theme1.isSelected()||theme2.isSelected()||theme3.isSelected()){
            if(theme1.isSelected()){
                i = new ImageIcon("D:\\stick fight\\gamephotos\\backdesert.jpg");
            }
            if(theme2.isSelected()){
                i = new ImageIcon("D:\\stick fight\\gamephotos\\backhills.jpg");
            }
            if(theme3.isSelected()){
                i = new ImageIcon("D:\\stick fight\\gamephotos\\backcity.jpg");
            }
            count++;            
        }
        else{
            JOptionPane.showMessageDialog(this, "please choose a theme");
            clear();
        }
        if(count==3){
            stickfight obj = new stickfight();
            obj.setVisible(true);
            super.setVisible(false);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frontpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frontpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frontpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frontpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frontpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel b1;
    public static javax.swing.ButtonGroup bg1;
    private javax.swing.JLabel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel l1;
    private javax.swing.JTextField p1n;
    private javax.swing.JTextField p2n;
    public static javax.swing.JRadioButton theme1;
    public static javax.swing.JRadioButton theme2;
    public static javax.swing.JRadioButton theme3;
    // End of variables declaration//GEN-END:variables
}
