import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        t3 = new javax.swing.JPasswordField();
        t4 = new javax.swing.JPasswordField();
        tc = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Name:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(55, 80, 52, 20);

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Username:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(55, 118, 70, 30);

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Password:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(55, 156, 60, 30);

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("<html> <body> Confirm <br> Password: </body> </html> ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(55, 194, 60, 40);

        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1KeyTyped(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(137, 77, 105, 30);

        t2.setToolTipText("must be between 8 - 40 characters");
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2);
        t2.setBounds(137, 115, 105, 30);

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("E-Mail ID");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(55, 248, 50, 30);
        getContentPane().add(t5);
        t5.setBounds(137, 245, 169, 30);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 320, 70, 23);

        t3.setToolTipText("must be between 8 - 15 characters");
        getContentPane().add(t3);
        t3.setBounds(137, 153, 105, 30);
        getContentPane().add(t4);
        t4.setBounds(137, 202, 105, 30);

        tc.setForeground(new java.awt.Color(240, 240, 240));
        tc.setText("I Agree to the terms and conditions.");
        tc.setOpaque(false);
        tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcActionPerformed(evt);
            }
        });
        getContentPane().add(tc);
        tc.setBounds(80, 290, 220, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SignUp Page");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 30, 140, 22);

        back.setIcon(new javax.swing.ImageIcon("D:\\stick fight\\gamephotos\\backlogsign.jpg")); // NOI18N
        back.setOpaque(true);
        getContentPane().add(back);
        back.setBounds(0, -10, 400, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed
// for name field
    private void t1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyTyped
        int kc = evt.getKeyChar();
        if(((kc<'a')||(kc>'z'))&&((kc<'A')||(kc>'Z'))&&(kc!='\b')&&(kc!=' ')){
            JOptionPane.showMessageDialog(this,"Enter only alphabets");
        }
    }//GEN-LAST:event_t1KeyTyped
// submit button:
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int check = 0;
        int usercheck = 0;
        String name = t1.getText();
        String username = t2.getText();
        String password = new String(t3.getPassword());
        String password2 = new String(t4.getPassword());
        String emailid = t5.getText();
        if(!((name.equals(""))||(username.equals(""))||(password.equals(""))||(password2.equals(""))||(emailid.equals("")))){
            check++;
        }
        else{
            JOptionPane.showMessageDialog(this, "Please do not leave any of the fields empty");
        }
        if(password.equals(password2)){
            check++;
        }
        else{
            JOptionPane.showMessageDialog(this, "passwords don't match");
        }
        if((username.length()>=8)&&(username.length()<=40)&&(password.length()>=8)&&(password.length()<=15)){
            check++;
        }
        else{
            JOptionPane.showMessageDialog(this, "username and password must be between the specified limit"+"\n"+
                    "move cursor over fields to view the size");
        }
        if(tc.isSelected()){
            check++;
        }
        else{
            JOptionPane.showMessageDialog(this, "Please agree to the terms and conditions");
        }
        if(check==4){
            try{
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/useraccounts","root","mysql");
                Statement st = con.createStatement();
                String query1 = "select username from acc";
                ResultSet rs = st.executeQuery(query1);
                while(rs.next()){
                    if(username.equals(rs.getString(1))){
                        usercheck++;
                        JOptionPane.showMessageDialog(this, "Sorry, username already taken. Please try another one.");
                        break;
                    }
                }
                if(usercheck==0){
                    String query2 = "Insert into acc values('"+name+"','"+username+"','"+password+"','"+emailid+"');";
                    st.executeUpdate(query2);
                }
                JOptionPane.showMessageDialog(this, "you have successfully signed up");
                Login obj = new Login();
                obj.setVisible(true);
                super.setVisible(false);
            }
            catch(Exception e){
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        super.setSize(400,390);
    }//GEN-LAST:event_formWindowOpened

    private void tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JPasswordField t3;
    private javax.swing.JPasswordField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JCheckBox tc;
    // End of variables declaration//GEN-END:variables
}
