import java.awt.Color;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.Timer;
import javax.swing.JOptionPane;
import java.lang.Math;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class fb extends javax.swing.JFrame {

    int x = 10,y = 200,size = 20;
    int score = 0;
    int p1x = 200,p3x = 308,p5x = 416,p7x = 524,p9x = 632;
    int p2y,p4y,p6y,p8y,p10y;
    int p1h = 190, p2h,p3h = 150,p4h,p5h = 170,p6h,p7h = 110,p8h,p9h = 130,p10h;
    
    int[] p1height = {120,130,140,150,160,170,180,190,200,210,220,230,240,250,260,270,280};
    /**
     * Creates new form fb
     */
    public fb() {
        initComponents();
        setSize(500,550);
        jButton1.setLocation(20,515);
        jButton2.setLocation(80,515);
        jLabel1.setLocation(140,515);
        setResizable(false);
        Random r = new Random();
        int k = 0+r.nextInt(17);
        p1h = p1height[k];
    }

    public void paint(Graphics g){
        p2y = p1h+120;
        p4y = p3h+120;
        p6y = p5h+120;
        p8y = p7h+120;
        p10y = p9h+120;
        p2h = 500-p2y;
        p4h = 500-p4y;
        p6h = 500-p6y;
        p8h = 500-p8y;
        p10h = 500-p10y;
        
        g.clearRect(super.getX(),super.getY(),super.getWidth(),super.getHeight());
        g.drawLine(0,500,500,500);
        g.drawLine(0,501,500,501);
        g.drawString("score: "+score, 140, 515);
        
        g.fillOval(x,y,size,size);       
        g.setColor(Color.green);
        g.fillRect(p1x,0,35,p1h);
        g.fillRect(p1x,p2y,35,p2h);
        g.fillRect(p3x,0,35,p3h);
        g.fillRect(p3x,p4y,35,p4h);
        g.fillRect(p5x,0,35,p5h);
        g.fillRect(p5x,p6y,35,p6h);
        g.fillRect(p7x,0,35,p7h);
        g.fillRect(p7x,p8y,35,p8h); 
        g.fillRect(p9x,0,35,p9h);
        g.fillRect(p9x,p10y,35,p10h);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Score: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addGap(35, 35, 35)
                .addComponent(jButton2)
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(277, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
ActionListener action;
Timer t;
int init = 0;
int i,ichange = 1;
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        i = 6;
        ichange = 1;
        action = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                i-=ichange;
                if(i==0){
                    ichange = -1;
                    i=1;
                }
                if(i>6){
                    y+=20;
                }
                else{          
                    y -= ichange*(i*i);
                }
                repaint();
            }
        };
        
        if(init==0){
            t = new Timer(1,action);
            jButton1.doClick();
            init = 1;
        }
        t.setDelay(60);
        t.setRepeats(true);
        t.start();
        
    }//GEN-LAST:event_formMouseClicked
ActionListener pipe;
Timer t2;
int init2 = 0;
int[] updown = {1,-1};
Random r;
int sign,psn;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        pipe = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                p1x--;
                p3x--;
                p5x--;
                p7x--;
                p9x--;
                
                if(p1x<=(-35)){
                    p1x = 500;
                    if(p9h<=100)
                        psn = 1;
                    else if((p9h+120)>=400)
                        psn = -1;
                    else{
                        r = new Random();
                        sign = 0+r.nextInt(2);
                        psn = updown[sign];
                    }
                    p1h = p9h + (int)(60*Math.random()*psn);
                }
                else if(p3x<=(-35)){
                    p3x = 500;
                    if(p1h<=100)
                        psn = 1;
                    else if((p1h+120)>=400)
                        psn = -1;
                    else{
                        r = new Random();
                        sign = 0+r.nextInt(2);
                        psn = updown[sign];
                    }
                    p3h = p1h + (int)(60*Math.random()*psn);
                }
                else if(p5x<=(-35)){
                    p5x = 500;
                    if(p3h<=100)
                        psn = 1;
                    else if((p3h+120)>=400)
                        psn = -1;
                    else{
                        r = new Random();
                        sign = 0+r.nextInt(2);
                        psn = updown[sign];
                    }
                    p5h = p3h + (int)(60*Math.random()*psn);
                }
                else if(p7x<=(-35)){
                    p7x = 500;
                    if(p5h<=100)
                        psn = 1;
                    else if((p5h+120)>=400)
                        psn = -1;
                    else{
                        r = new Random();
                        sign = 0+r.nextInt(2);
                        psn = updown[sign];
                    }
                    p7h = p5h + (int)(60*Math.random()*psn);
                }
                else if(p9x<=(-35)){
                    p9x = 500;
                    if(p7h<=100)
                        psn = 1;
                    else if((p7h+120)>=400)
                        psn = -1;
                    else{
                        r = new Random();
                        sign = 0+r.nextInt(2);
                        psn = updown[sign];
                    }
                    p9h = p7h + (int)(60*Math.random()*psn);
                }
                
                if((y<=0)||(y+size>=500)){
                    t2.stop();
                    t.stop();
                    JOptionPane.showMessageDialog(null,"game over");                   
                }
                
                if((y<=p1h)&&(x+size>=p1x)&&(x<=p1x+35)){
                    t2.stop();
                    t.stop();
                    JOptionPane.showMessageDialog(null,"game over");
                }
                if((y<=p3h)&&(x+size>=p3x)&&(x<=p3x+35)){
                    t2.stop();
                    t.stop();
                    JOptionPane.showMessageDialog(null,"game over");
                }
                if((y<=p5h)&&(x+size>=p5x)&&(x<=p5x+35)){
                    t2.stop();
                    t.stop();
                    JOptionPane.showMessageDialog(null,"game over");
                }
                if((y<=p7h)&&(x+size>=p7x)&&(x<=p7x+35)){
                    t2.stop();
                    t.stop();
                    JOptionPane.showMessageDialog(null,"game over");
                }
                if((y<=p9h)&&(x+size>=p9x)&&(x<=p9x+35)){
                    t2.stop();
                    t.stop();
                    JOptionPane.showMessageDialog(null,"game over");
                }
                
                if((y+size>=p2y)&&(x+size>=p1x)&&(x<=p1x+35)){
                    t2.stop();
                    t.stop();
                    JOptionPane.showMessageDialog(null,"game over");
                }
                if((y+size>=p4y)&&(x+size>=p3x)&&(x<=p3x+35)){
                    t2.stop();
                    t.stop();
                    JOptionPane.showMessageDialog(null,"game over");
                }
                if((y+size>=p6y)&&(x+size>=p5x)&&(x<=p5x+35)){
                    t2.stop();
                    t.stop();
                    JOptionPane.showMessageDialog(null,"game over");
                }
                if((y+size>=p8y)&&(x+size>=p7x)&&(x<=p7x+35)){
                    t2.stop();
                    t.stop();
                    JOptionPane.showMessageDialog(null,"game over");
                }
                if((y+size>=p10y)&&(x+size>=p9x)&&(x<=p9x+35)){
                    t2.stop();
                    t.stop();
                    JOptionPane.showMessageDialog(null,"game over");
                }               
                
                if((x>=p1x)&&(score%5==0)){
                    jLabel1.setText("score: "+score);
                    score++;
                }
                else if((x>=p3x)&&(score%5==1)){
                    jLabel1.setText("score: "+score);
                    score++;
                }
                else if((x>=p5x)&&(score%5==2)){
                    jLabel1.setText("score: "+score);
                    score++;
                }
                else if((x>=p7x)&&(score%5==3)){
                    jLabel1.setText("score: "+score);
                    score++;
                }
                else if((x>=p9x)&&(score%5==4)){
                    jLabel1.setText("score: "+score);
                    score++;
                }
                repaint();
            }
        };
        
        if(init2==0){
            t2 = new Timer(1,pipe);
            init2 = 1;
        }
        t2.setDelay(20);
        t2.setRepeats(true);
        t2.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        x = 10;y = 200;size = 20;score = 0;
        p1x = 200;p3x = 308;p5x = 416;p7x = 524;p9x = 632;
        Random r = new Random();
        int k = 0+r.nextInt(17);
        p1h = p1height[k];
        p3h = 150;p5h = 170;p7h = 110;p9h = 130;
        repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
